# Generated by Django 5.2 on 2025-04-27 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Asset',
        ),
    ]
