// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

type UploadModalData struct {
	LibraryPublicID string
}

func UploadModal(data UploadModalData) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<dialog id=\"upload_modal\" class=\"modal\"><div class=\"modal-box max-w-4xl\"><h3 class=\"font-bold text-lg mb-4\">File Upload</h3><input type=\"hidden\" id=\"libraryPublicID\" value=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(data.LibraryPublicID)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `upload_modal.templ`, Line: 11, Col: 73}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "\"><div class=\"my-4\"><div id=\"uploader\"></div></div><div class=\"modal-action\"><form method=\"dialog\" style=\"display: inline;\"><button class=\"btn\" id=\"close_upload_modal\">Close</button></form></div></div><link href=\"https://releases.transloadit.com/uppy/v3.21.0/uppy.min.css\" rel=\"stylesheet\"><script type=\"module\">\n\t\t\timport { Uppy, Dashboard, XHRUpload } from \"https://releases.transloadit.com/uppy/v3.21.0/uppy.min.mjs\"\n\n\t\t\tconst uppy = new Uppy({\n\t\t\t\trestrictions: {\n\t\t\t\t\tmaxNumberOfFiles: 5000\n\t\t\t\t},\n\t\t\t\tautoProceed: false\n\t\t\t})\n\t\t\t.use(Dashboard, {\n\t\t\t\tinline: true,\n\t\t\t\ttarget: '#uploader',\n\t\t\t\tshowProgressDetails: true,\n\t\t\t\tproudlyDisplayPoweredByUppy: false,\n\t\t\t\theight: 400,\n\t\t\t\tnote: 'Up to 5000 files'\n\t\t\t})\n\t\t\t.use(XHRUpload, {\n\t\t\t\tendpoint: '/assets/upload',\n\t\t\t\tfieldName: 'files',\n\t\t\t\tformData: true,\n\t\t\t\tbundle: true,\n\t\t\t\t// This function runs before each upload, allowing us to modify the request.\n\t\t\t\tprepareRequest: (files, req) => {\n\t\t\t\t\tconst libraryPublicID = document.getElementById('libraryPublicID').value;\n\t\t\t\t\tif (libraryPublicID) {\n\t\t\t\t\t\treq.formData.append('libraryPublicID', libraryPublicID);\n\t\t\t\t\t}\n\t\t\t\t\treturn req;\n\t\t\t\t}\n\t\t\t})\n\n\t\t\tuppy.on('complete', (result) => {\n\t\t\t\tconsole.log('Upload complete:', result)\n\t\t\t\tif (result.successful.length > 0) {\n\t\t\t\t\t// Reload the page to show new uploads\n\t\t\t\t\twindow.location.reload()\n\t\t\t\t}\n\t\t\t})\n\n\t\t\t// Close modal when close button is clicked\n\t\t\tdocument.getElementById('close_upload_modal').addEventListener('click', () => {\n\t\t\t\tuppy.cancelAll()\n\t\t\t})\n\t\t</script></dialog>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
